version: '3.8'

services:
  db:
    image: mariadb:11
    environment:
      MARIADB_USER: 'example-user-kenneth'
      MARIADB_PASSWORD: 'my_cool_secret'
      MARIADB_ROOT_PASSWORD: 'root'
      MARIADB_DATABASE: 'zay_db'
    volumes:
      - ./db:/var/lib/mysql

  frontend-app:
    image: cl-exam-frontend
    ports:
      - 5002:80
    depends_on:
      - backend-app
      - db

  backend-app:
    image: cl-exam-backend
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
        PORT: 3000
        DB_HOSTNAME: db
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_DATABASE: zay_db
    command: sh -c "npm run db:migrate && npm run db:seed && npm run start"